[pytest]
testpaths = tests
python_files = test_*.py
norecursedirs =
    .git
    .pytest_cache
    .pytest*
    .test-*
    .test_*
    .tmp*
    qa
    frontend
    node_modules
    var
    reports
    outputs
addopts = --strict-config --strict-markers
